<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity] // Tell the Doctrine "this class represents a table"
#[ORM\Table(name: 'users')] // Specifies which database table this class represents

class User {
    #[ORM\Id] // Marks "$id" as the table's primary key
    #[ORM\GeneratedValue] // It states that the value of this variable is automatically generated by the database
    #[ORM\Column(type: 'integer')]
    private int $id;

    #[ORM\Column(type: 'string', length: 50)]
    private string $name;

    #[ORM\Column(type: 'string', length: 50)]
    private string $surname;

    #[ORM\Column(type: 'string', length: 50)]
    private string $username;

    #[ORM\Column(type: 'integer')]
    private int $phone;
    
    #[ORM\Column(type: 'integer')]
    private int $age;

    #[ORM\Column(type: 'string', length: 250, unique:true)]
    private string $email;

    #[ORM\Column(type: 'string', length: 250)]
    private string $password;

    public function getId(): int {
        return $this->id;
    }

    public function getName(): string {
        return $this->name;
    }

    public function setName(string $name): static {
        $this->name = $name;
        return $this;
    }

    public function getSurname(): string {
        return $this->surname;
    }

    public function setSurname(string $surname): static {
        $this->surname = $surname;
        return $this;
    }

    public function getUsername(): string {
        return $this->username;
    }

    public function setUsername(string $username): static {
        $this->username = $username;
        return $this;
    }

    public function getPhone(): string {
        return $this->phone;
    }

    public function setPhone(string $phone): static {
        $this->phone = $phone;
        return $this;
    }
    
    public function getAge(): int {
        return $this->age;
    }

    public function setAge(int $age): static {
        $this->age = $age;
        return $this;
    }

    public function getEmail(): string {
        return $this->email;
    }

    public function setEmail(string $email): static {
        $this->email = $email;
        return $this;
    }
    
    public function getPassword(): string {
        return $this->password;
    }

    public function setPassword(string $password): static {
        $this->password = $password;
        return $this;
    }
}

?>